traefik:
  ingressRoute:
    dashboard:
      enabled: true
  ports:
    web:
      http:
        redirections:
          entryPoint:
            to: websecure
            scheme: https
            permanent: true
    websecure:
      http:
        tls:
          enabled: true
