external-dns:
  # Configure for your DNS provider. Examples:
  # provider:
  #   name: aws
  # provider:
  #   name: cloudflare
  #   cloudflare:
  #     secretName: cloudflare-api-key
  provider:
    name: aws
  policy: upsert-only
  sources:
    - ingress
    - service
